runtime: nodejs12

service: governance-app

handlers:
  - url: /(.*\.(gif|png|svg|ttf|jpeg|jpg|css|css.map|js|js.map|pdf|scss|ico|json|json.map|mp4|webm))$
    static_files: build/\1
    args: ['--ignore-engines']
    secure: always
    upload: build/(.*)
    http_headers:
      X-Frame-Options: deny
  - url: /(.*)
    static_files: build/index.html
    args: ['--ignore-engines']
    secure: always
    upload: build/index.html
    http_headers:
      X-Frame-Options: deny
